Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job stats:
job                 count
----------------  -------
all                     1
scanpy_read_data        1
seurat_read_data        1
total                   3

Select jobs to execute...

[Wed Jul 24 18:49:02 2024]
rule seurat_read_data:
    input: data/raw/seurat_input.rds
    output: data/processed/seurat/01_read_data.rds
    log: logs/seurat/01_read_data.log
    jobid: 1
    reason: Missing output files: data/processed/seurat/01_read_data.rds
    resources: tmpdir=/tmp

[Wed Jul 24 18:49:02 2024]
rule scanpy_read_data:
    input: data/raw/scanpy_input.h5ad
    output: data/processed/scanpy/01_read_data.h5ad
    log: logs/scanpy/01_read_data.log
    jobid: 2
    reason: Missing output files: data/processed/scanpy/01_read_data.h5ad
    resources: tmpdir=/tmp

[Wed Jul 24 18:49:43 2024]
Error in rule seurat_read_data:
    jobid: 1
    input: data/raw/seurat_input.rds
    output: data/processed/seurat/01_read_data.rds
    log: logs/seurat/01_read_data.log (check log file(s) for error details)

RuleException:
CalledProcessError in file /mnt/exfat01/projects/scRNA-0722/seurat.smk, line 12:
Command 'set -euo pipefail;  Rscript --vanilla /mnt/exfat01/projects/scRNA-0722/.snakemake/scripts/tmphdaazf9f.01_read_data.R' returned non-zero exit status 1.
  File "/mnt/exfat01/projects/scRNA-0722/seurat.smk", line 12, in __rule_seurat_read_data
  File "/opt/miniforge3/envs/scanpy/lib/python3.9/concurrent/futures/thread.py", line 58, in run
[Wed Jul 24 18:49:51 2024]
Finished job 2.
1 of 3 steps (33%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-07-24T184902.594670.snakemake.log
